package com.kie_pract.incentivetest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class asdasdsd implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public asdasdsd() {
    }




}